### ISSUE TITLE
No search field

### ISSUE THREAD

**Issue by irgendwie** [owncloud/mail#1057]
Starting from owncloud 8.1, the search bar is missing for the mail app. Therefore search for mails is not possible anymore.

Maybe caused by by: owncloud/core#16810

Edit: This also happens for some other apps, like contacts, bookmarks, etc.
It works for example with the files app and the tasks app.

**Comment by jancborchardt** [comment]
@DeepDiver1975 @ChristophWurst @Gomez any idea here?

**Comment by DeepDiver1975** [comment]
This was for sure working some weeks back .....

**Comment by ChristophWurst** [comment]
5fd5ab6c5e17fb43bcb7c7b9b379f8bcc76d1109 caused it. I must have forgotten something…

**Comment by irgendwie** [comment]
Oh, you're right - didn't check for an old mail version >.<
So no 8.1 problem :+1:

**Comment by ChristophWurst** [comment]
Ok, this is totally strange. The 'plugin' is registered like before, I even checked the passed object and it's the initialized 'Search' module (having both ``attach`` and ``filter`` method). I don't see why this doesn't work anymore.

@PVince81 since this issue came with introducing requirejs, could it be that there's a timing issue? I could think of something like we're 'too late', like the on-page-load-event has already been fired and no plugins can be registered afterwards. This is the only thing that I could think of at the moment since we're loading our modules asynchronously… There isn't really anything I changed apart from that.

Btw. ``attach`` and ``filter`` are never called on our search module.

**Comment by irgendwie** [comment]
Seems to work again with the current master :+1:

Still **sometimes!** when I search and there are no results it shows
"No search results for {{searchTerm}}",
again sometimes the searchTerm is correctly replaced with my search term.
Ideas? @ChristophWurst

**Comment by ChristophWurst** [comment]
@irgendwie when it does work, are you using the optimized js file or source files? (debug mode off or on)

**Comment by ChristophWurst** [comment]
@PVince81 ping ^

**Comment by ChristophWurst** [comment]
Seems to work if you use the minified js version. This supports my suspicion that this bug is a timing issue.
