### ISSUE TITLE
Error Message "Server error" is shown - mail was sent

### ISSUE THREAD

**Issue by riotweb** [owncloud/mail#1244]
After sending a Mail the "Server error" is shown on the top bar. 
The Mail was sent. 

I tryed with an address from my oc contacts - and an other address. All works - but always the error message is shown.

additionaly the Text stays in the form, so I can resend the mail again and again.

**Comment by ChristophWurst** [comment]
Hi @riotweb,
thanks for reporting! Please fill out the [issue template](https://raw.githubusercontent.com/owncloud/mail/master/issue_template.md) so we get more information about your setup. This will help us identify the bug.

If the mail is being sent, there might be a problem with saving the sent message to the 'Sent'-folder.

**Comment by riotweb** [comment]
Sorry for my late answer.
In version 0.3 it wors now.
Thank you!

**Comment by hrishikeshnb** [comment]
Faced similar issue in version 8.2.2
I'm able to successfully send an email within our particular domain(company domain). 
But if I try send an email to any third party domain like @gmail.com or @yahoo.com it shows "Server Error" message, but the mail is actually sent to that particular gmail or yahoo id.
In the error logs the following message pops up : "Sending mail failed: Error when communicating with the server."

So how should I fix this, so that these mails show a positive "SENT" response and get accumulated in the Sent folder ?

**Comment by ChristophWurst** [comment]
Hi @hrishikeshnb,
please fill out the issue template and provide owncloud and horde logs so someone can have a look at it. Thanks.

**Comment by hrishikeshnb** [comment]
The following one , right ? 
https://raw.githubusercontent.com/owncloud/mail/master/issue_template.md
And to whom should I send these details ?

**Comment by ChristophWurst** [comment]
Yes, exactly. Post it here please so anybody can have a look. Make sure you remove sensitive information (e.g. passwords, mail addresses).
