### ISSUE TITLE
Change special folders manually

### ISSUE THREAD

**Issue by feluxe** [owncloud/mail#1246]
I could not find an option to change the folders that owncloud/mail uses for "Sent", "Drafts", etc.
Right now there are three sets of special folders under my account. One set inside "Inbox", one set outside "Inbox" (with icons) and another set outside "Inbox" (without icons). The last one is actually the only set I like to use.

If there is no option to change special folders manually I would suggest one.

![owncloudmail](https://cloud.githubusercontent.com/assets/6545589/12641214/8d49e98e-c5ae-11e5-8f14-60d6684f77b0.jpg)

**Comment by ChristophWurst** [comment]
Hi @feluxe,
thanks for reporting this enhancement. Currently special folders are guessed by either their role, provided that the IMAP server supports it, or by the name of the folder.

I can think of two possible solutions to your problem:

1. make it possible to change folder roles
    - downside: not all IMAP server support it
2. keep a list of folders in the databse and add a role-attribute
    - downside: could be tricky to keep local folders in sync with IMAP ones

@owncloud/mail what do you think? Is there any easier way?

**Comment by feluxe** [comment]
Hi Christoph,

some more background on this:

I'm using different Mail Clients on the same IMAP account. Thunderbird on my Laptop, K9 Mail on my Smartphone and owncloud/mail (before I used Roundcube) to get browser access to the mails, which is important to me. All of these mail clients tended to mess around with the special folders by default. There was no consistency among them, so I created my own special folders called: sent@server, draft@server, etc. and made each Mail Client to use these as the default ones. Thunderbird, K9 and Roundcube all let you define special folders manually. It works very well, except for owncloud/mail.

**Comment by jancborchardt** [comment]
The problem seems to be that you chose non-standard names, with the »@server« appended. ownCloud Mail actually works nicely by default with many providers because it just checks the common names like »Sent«, »Drafts«, »Trash« etc.

When your folders are simply named like that, there will be no problem. And other clients like Thunderbird and K-9 shouldn’t have a problem with that either. :)

**Comment by feluxe** [comment]
@jancborchardt 
I tried with "standard" names (Sent, Drafts, Junk, Trash, Archive, etc.) but that didn't work well. I always ended up with a couple extra folders created as default by different clients. One calls it "Junk E-Mail" one calls it just "Junk", one puts it into the "Inbox" folder one puts it outside of it, etc. There was no complete standard among the Mail Clients that I could use without hassle. So in order to identify the correct folders I added "@server" to them and force the clients to move the mails there. It works well. Whenever another "Sent" or "Drafts" folder appears (like in case of owncloud/mail) I can identify the correct ones immediately. Otherwise it is very hard to tell. 

![roundcube](https://cloud.githubusercontent.com/assets/6545589/12651573/5c3db0e4-c5e7-11e5-9409-9c62d7b98dd7.jpg)
![thunderbird](https://cloud.githubusercontent.com/assets/6545589/12651574/5c558818-c5e7-11e5-897c-723fc45fdbc1.jpg)

**Comment by jancborchardt** [comment]
You can add your custom folder names in the `lib/mailbox.php` file: https://github.com/owncloud/mail/blob/master/lib/mailbox.php#L311-L317

Fixing this in our app would make no sense because it’s a fix just for you. ;) The real problem here are the other apps, so probably best to open an issue at their bug tracker so you don’t even need such a specific setup.
