### ISSUE TITLE
Sub-sub and Sub-sub-sub-....... folders

### ISSUE THREAD

**Issue by hanslammerts** [owncloud/mail#1279]
Hi,

Great work on solving the issue that mails were not loaded when selecting sub-sub folders or deeper !
I can now see and read my mails.
However, are there any plans to construct the folder tree in such a way that sub-sub folders (and deeper) are really shown as a subfolder, which has another folder or folders inside ?

Sub-sub folders and deeper are now displayed as Subfolder1.subfolderA.subfolder and
Subfolder1.subfolderB.subfolder.
In my case there are quite some subfolders that have subfolders that have subfolders...etc.
Since the foldername displayed gets very long, and the left pane is not resizable, sometimes I can not see where I am.

Regards,
Hans

**Comment by ChristophWurst** [comment]
Hi @hanslammerts,
this is by design, see https://github.com/owncloud/mail/issues/618#issuecomment-99271478

cc @jancborchardt

**Comment by jancborchardt** [comment]
We could show a tooltip for very long folder names. I’d prefer if this really only shows up when the folder name is longer than can be displayed since otherwise it’s not needed. This requires additional JS and is definitely not a high priority.

And we don’t want to show a tree-like sub-sub-sub folder structure etc. :) Our goal with ownCloud Mail is not to just apply the same concepts as old email apps with all their problems and complexity. We want to modernize the approach a bit while still being approachable also to high-volume email users. But deep nesting is not part of that. :)

**Comment by hanslammerts** [comment]
Hmm, pity....


Verzonden vanaf mijn Samsung-apparaat

-------- Oorspronkelijk bericht --------
Van: Christoph Wurst <notifications@github.com> 
Datum: 08-02-2016  16:41  (GMT+01:00) 
Aan: owncloud/mail <mail@noreply.github.com> 
Cc: hanslammerts <j.lammerts@chello.nl> 
Onderwerp: Re: [mail] Sub-sub and Sub-sub-sub-....... folders (#1279) 

Hi @hanslammerts,

this is by design, see #618 (comment)

cc @jancborchardt

**Comment by jancborchardt** [comment]
@hanslammerts if you know a developer who wants to implement it – very welcome! :) I didn’t say we’ll never do it, but our focus is clearly on more core features for quite some time still.

**Comment by hanslammerts** [comment]
Wish I knew one. I understand your views and hope someday someone will implement this.


Verzonden vanaf mijn Samsung-apparaat

-------- Oorspronkelijk bericht --------
Van: Jan-Christoph Borchardt <notifications@github.com> 
Datum: 08-02-2016  22:10  (GMT+01:00) 
Aan: owncloud/mail <mail@noreply.github.com> 
Cc: hanslammerts <j.lammerts@chello.nl> 
Onderwerp: Re: [mail] Sub-sub and Sub-sub-sub-....... folders (#1279) 

@hanslammerts if you know a developer who wants to implement it – very welcome! :) I didn’t say we’ll never do it, but our focus is clearly on more core features for quite some time still.
