### ISSUE TITLE
[suggestion] Mailview / look/style of the mail view 

### ISSUE THREAD

**Issue by blackcrack** [owncloud/mail#1402]
Hi,

i want suggestion different style of the mail/view/look/style how ever..
with id' can you load different style of html-code, why not this use as a
possibility for configure 3,4 different style of the look of the mail ?

id=1 the actual look and feel
id=2 (like in thunderbird)
one view, on top-right the listing of the mails,
left the whole accounts and right bottom the 
viewport of the single mails if it's klicked on

id=3
maybe like on outlook

id=4 and so on ..

and in a cooki can setting up which id it's prefer 
with mail_style_viewport or maybe
as a ini/text in the account of the user(if works..) 
for have a choice which look and feel the user want have..
(sex sells, style sells also ;) ) 

best regards
Blacky

**Comment by jancborchardt** [comment]
This would not only entail the work in actually doing it, but also maintaining the view.

Apart from that, the view we currently have is the one we consider best and which most well-designed email apps actually also use (Apple Mail app, Geary/Pantheon mail etc).

cc @ChristophWurst @Gomez

**Comment by blackcrack** [comment]
well we are all not in apple, the world it's huge and it's give different view on that .. what's really well,
it's not up to you to decision that , it's the user and the consumer, it's up to they are what they whant view and what not.. i have give only a suggestion..

**Comment by ChristophWurst** [comment]
Hi @blackcrack!
Thanks for your suggestion. We try our best to create a simple to use mail application, following [ownCloud's guidelines](https://doc.owncloud.org/server/9.0/developer_manual/general/codingguidelines.html). Hence, we prefer to have a well designed view that works best for most users instead of having that as a configuration option.

**Comment by blackcrack** [comment]
Hi Christoph,
thank you for you nice answer ..
and.. for the pretty well explaining !  :+1: 

thank you very much..
have a nice day
and best regards
Christoph

and the deepdiver's changed of the title helps not really..

**Comment by jancborchardt** [comment]
> and by the way, why t.h. do you ever meant to work ever against some suggestion and why ever must you the one be, who meant he mus it be where decides and make it bad and the one where mus ever interfere

Well, as Christoph explained. I don’t work against all suggestions, I try to explain why we design it the way we do. But yeah, as I am the main designer, I do make decisions like these which can not please everyone all the time. Unfortunately with design the case is that many people have an opinion on it, unlike code & function writing.

We are not a big software company nor a big team, so we can not maintain so many different views. We develop things we like to use for ourselves. And we would simply not use all these views either, so at some point they would fall into disarray.

As much as I hate falling back to the old saying – in the end it’s open source and you are free to modify it.

**Comment by blackcrack** [comment]
well, you a young one, maby should you think about to do less decisions for other
and make therewith a more huge world for other.. to you not think about, that you could otherwise crush
on a possible huge meadow of difference wonderful and possible possibility .. for others too ..

may be a open source, but wenn man manches unterbindet
if one prevents something, it is not possible for growing up..

**Comment by DeepDiver1975** [comment]
In addition to any design reason why we should not introduce different views as of now is that the code will grow and will be much harder to maintain. We already had big apps in the past with could not longer be maintained because they where simply to big (yes - not the only reason - but one).

Furthermore I'd like to see any resources being invested into feature which are really missing as of today.

@blackcrack join the force and help out to build the cool version of the mail app - THX

**Comment by blackcrack** [comment]
well.. i have 8 and 12 Shifts and have no time anymore since a couple month to join the force and be totally at ...... if i come hime.. and the couple day's where i have, have i to take for go take a Drink with ma old dad in the next big City and the other day have i take to rest.. and the owncloud it is the right Webapplication now where it is on the right time and place for use for my handy's and other webpossibilitys to connect on my own server.. and i need it and the time what i have for free, this wont i use with "Security&Savety" for rest me... in the couple of years now because more as 15 Years on the Computer it's a long time.. and it is now ago.. for making money now..
so, be the force with you Jedi .. THX, i can give only now inspirations and suggetions .
best regards
Blacky

**Comment by jancborchardt** [comment]
@blackcrack sure. Please understand that we too don’t have an overabundance of time for everything. :) And just to get to your points:

> well, you a young one, maybe should you think about to do less decisions for other
and make therewith a more huge world for other.

Do not mistake my age for lack of experience. I have plenty of design experience, a bunch of open source experience, and worked in enough projects (and know people from many more) to know a bit about what makes it fail and thrive.


> main designer, should you look for the code, to be able for nice and really and be well possible design the surface, and setting up the class and id's for give to make well different disighn's
later and make it able for be all clean and fit's in the code, for make possible to make very nice skin's

Well, this we do and it’s possible. See theming: https://github.com/owncloud/core/tree/master/themes

> this should be your job, but a restricting of surfacedesign it's maby somethimes not so well, especially if it should be done, that there should be different surfaces for look and ffeel, the coloring and skinning should on this step fitting with correct class'es and id's in the php code. The programmers should be decide for themselves what they want to assemble or not.

My job is making ownCloud easily usable for normal people. Not to make it easily configurable for advanced people with development experience.

See the »Design guidelines« section on our ownCloud design page: https://owncloud.org/contribute/design/


> ... maybe a open source, but If it eliminates some/ if one prevents something, it is not possible for growing up.. and it arises never .. ... it mus all be like a "Arier" he.. hit.. blonde, blue eyes and hard like Win10 desighn, ready for commerz..yess..

One of the big reasons why ownCloud is so big is because it’s as simple to use as comparable proprietary offerings. I’ll ignore the nazi reference cause it’s really uncalled for.
