### ISSUE TITLE
Error: this app cannot be enabled because it makes the server unstable

### ISSUE THREAD

**Issue by DocMAX** [owncloud/mail#1522]
Error: this app cannot be enabled because it makes the server unstable

this is what i get on latest owncloud 9.0.2

**Comment by ChristophWurst** [comment]
Hi @DocMAX,
please do not ignore the [issue template](https://github.com/owncloud/mail/blob/master/issue_template.md) when filing issues. Please use it and provide more information on you setup. Thanks

**Comment by fusenigk** [comment]
I get this error after installing a plain new own cloud 9.0.2 and installing the mail plugin. No further information are given.

**Comment by DocMAX** [comment]
fine, i'm not alone

**Comment by ChristophWurst** [comment]
In case one of you guys wants this issue fixed, provide the information we need using the issue template. Otherwise it is unlikely that anybody will have a look at this.

**Comment by viki53** [comment]
Same problem here with nightly build

---

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### ownCloud Mail

**ownCloud Mail version:** (see ownCloud apps admin page)

**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)

**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 

**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)

**Number of accounts:**

**ownCloud Mail version build date:** (only if you are using a Nightly Build)


### ownCloud Core

#### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:** 7.0.1

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

#### Client configuration
**Browser:**
Chr

**Operating system:**

#### Logs

##### ownCloud log (data/owncloud.log)
```
{"reqId":"hBXocgEKgYo9v2ZXRwOq","remoteAddr":"xxx.xx.xx.xxx","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Cannot include autoload. Did you run install dependencies using composer?\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(163): require_once()\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(144): OC_App::requireAppFile('mail')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(117): OC_App::loadApp('mail')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(866): OC_App::loadApps()\\n#4 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#5 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/mail\\\/appinfo\\\/app.php\",\"Line\":25}","level":3,"time":"2016-06-09T10:00:27+00:00","method":"GET","url":"\/index.php\/apps\/files","user":"admin"}
```

##### Browser log
```
* index.php/settings/ajax/enableapp.php
  Request Method:POST
  Status Code:200 OK
```

**Comment by viki53** [comment]
Same problem here with nightly build

---

### Steps to reproduce

1. Download zip form git repo (master branch)
2. Unzip into `apps` folder and rename
3. Activate app in admin page

N.B.: I had a previous install of the app, which was deactivated then removed (only the files, not the DB)

### Expected behaviour

App should be activated

### Actual behaviour

Error:

> Error: this app cannot be enabled because it makes the server unstable

### ownCloud Mail

**ownCloud Mail version:** 0.5.2

**Number of accounts:** ~2

**ownCloud Mail version build date:** June 9th (commit b0df8945a545b1f8dc4546478abb5a9c9ecb1290)


### ownCloud Core

#### Server configuration

**Operating system**: Debian Jessie

**Web server:** Apache 2

**Database:** MySQL

**PHP version:** 7.0.7-1

**ownCloud version:** 9.0.2

**Updated from an older ownCloud or fresh install:** Updated manually

**List of activated apps:**

```
- activity: 2.2.1
- bookmarks: true
- calendar: 1.2.2
- checksum: 2.0
- comments: 0.2
- contacts: 1.3.1.0
- dav: 0.1.6
- direct_menu: 0.7.1
- documents: 0.12.0
- encryption: 1.2.0
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_external: 0.5.2
- files_gdocs_viewer: 1.0
- files_mv: 0.8.2
- files_pdfviewer: 0.8.1
- files_sharing: 0.9.1
- files_texteditor: 2.1
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- gallery: 14.5.0
- logreader: 1.1.2
- news: 8.8.0
- notes: 2.0.1
- notifications: 0.2.3
- ownbackup: 0.3.8
- passwords: 18.0
- provisioning_api: 0.4.1
- search_lucene: 0.7.0
- systemtags: 0.2
- templateeditor: 0.1
- updatenotification: 0.1.0
- user_gravatar: 1.0
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ociwse9grgz1",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/home\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/my.server.ip.address\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "mail_from_address": "contact",
        "mail_smtpmode": "php",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": true,
        "theme": "",
        "maintenance": false,
        "loglevel": 0,
        "appstore.experimental.enabled": true,
        "trashbin_retention_obligation": "auto",
        "updatechecker": false
    }
}
```

#### Client configuration
**Browser:**

Chrome

**Operating system:**

Ubuntu 16.04 LTS

#### Logs

##### ownCloud log (data/owncloud.log)

```
{"reqId":"hBXocgEKgYo9v2ZXRwOq","remoteAddr":"xxx.xx.xx.xxx","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Cannot include autoload. Did you run install dependencies using composer?\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(163): require_once()\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(144): OC_App::requireAppFile('mail')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(117): OC_App::loadApp('mail')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(866): OC_App::loadApps()\\n#4 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#5 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/mail\\\/appinfo\\\/app.php\",\"Line\":25}","level":3,"time":"2016-06-09T10:00:27+00:00","method":"GET","url":"\/index.php\/apps\/files","user":"admin"}
```

##### Browser log

###### Network logs

```
/index.php/settings/ajax/enableapp.php
  Request Method: POST
  Status Code: 200 OK
/index.php/apps/files
  Request Method: GET
  Status Code: 500 Internal Server Error
```

**Comment by ChristophWurst** [comment]
> Cannot include autoload. Did you run install dependencies using composer?

@viki53 how did you install the app? Did you use a git clone?

**Comment by ChristophWurst** [comment]
> Download zip form git repo (master branch)

aaaah. That doesn't work. One has to install php,js dependencies and generated the minified js files.

**Comment by viki53** [comment]
So, I guess `composer install`, `npm install` and `grunt default`?

**Comment by ChristophWurst** [comment]
almost :P

Run those commands:
```bash
make install-composer-deps
make install-npm-deps-dev
make install-bower-deps
make optimize-js
```

**Comment by DocMAX** [comment]
i did git clone too. so that ist the problem...? i will check.

**Comment by ChristophWurst** [comment]
https://github.com/owncloud/mail#installation
https://github.com/owncloud/mail#developer-setup-info

**Comment by DocMAX** [comment]
i tried to install the normal way. but "mail" isnt included!

**Comment by ChristophWurst** [comment]
@DocMAX so what is the normal way?

**Comment by ChristophWurst** [comment]
Ok!

**Comment by ChristophWurst** [comment]
I will let people know that can fix that! Thanks!

**Comment by ChristophWurst** [comment]
Fixed!

**Comment by DocMAX** [comment]
thank you too for quick response
