### ISSUE TITLE
Is there a way to modify / delete an existing account?

### ISSUE THREAD

**Issue by simbro** [owncloud/mail#1614]
Is there a way to modify / delete an existing account?

**Comment by mar1u5** [comment]
Hi simbro,

Deleting Accounts is possible. (#1446) ...modifying is a bit #942 which is currently not possible. You need to delete a mailbox, and re-add it into the app 😉

**Comment by oppa1** [comment]
I was getting the "Error while loading the selected account" error (https://github.com/owncloud/mail/issues/1313) after I had changed my password on my server.

Since I couldn't even see the mail account in question (only a loading screen) using the fix from #1446 was impossible for me.
The only way to fix this was to drop the oc_mail_accounts table in my database and reinstall the mail app. I think there should be some way to manage accounts from the Settings menu (the gear icon).

**Comment by ChristophWurst** [comment]
> I think there should be some way to manage accounts from the Settings menu (the gear icon).

Deleting failing accounts will be possible with https://github.com/owncloud/mail/pull/1613
