### ISSUE TITLE
Feature Request: Collapse account while using multiple accounts

### ISSUE THREAD

**Issue by Pantos** [owncloud/mail#677]
I'm using mail with multiple mailaccounts. Because there are many folders it would be nice to collapse an account in the navigation bar on the left side to get a better overview.

Thanks for this great app!!

**Comment by Dark-Fenix** [comment]
+1 :)

**Comment by jancborchardt** [comment]
I’m thinking of a collapse-function which in the collapsed state would still be slightly useful and show the most important folders:
* Inbox
* Favorites (if there are any)
* Drafts (if there are any)

@wurstchristoph @zinks- @irgendwie what do you think?

**Comment by wurstchristoph** [comment]
@jancborchardt sounds good and is similar to what I described in #682 ;-)

**Comment by irgendwie** [comment]
@jancborchardt I also approve this! :+1:

**Comment by jancborchardt** [comment]
@wurstchristoph yeah, that’s also what I was going for! I know the Geary layout but don’t fully like it – I’m very hesitant of duplicating the inbox in the sidebar. So this might be a better solution.

So I would say rather than #682 we’d fare better with this »priority collapsing« combined with a unified inbox #120 (and maybe other unified folders). :) Maybe we can work on that next Wednesday! (Or before already, if you’re down for that. ;D

**Comment by jancborchardt** [comment]
Having 2 accounts _and_ a bunch of folders is pretty advanced (not as important as forwarding and adding attachments from local e.g.) – so postponing to 0.3
