### ISSUE TITLE
owncloud calendar and contacts

### ISSUE THREAD

**Issue by Kenarso** [owncloud/mail#765]
When will you implement the calendar and contacts in mail? Is there any timeframe?

**Comment by aidanamavi** [comment]
There is some integration right now, other work being done, and much work planned. It's a slow process, but you can search through open and closed issues to see what has been and will be accomplished, try out a Github developer build (master branch) to get a sneak peak, or wait until our next release. Contacts will see faster integration than Calendar, because Calendar is undergoing a major rewrite.

If there are any things you'd like to see done sooner than later, open a new issue for each specific feature request or add your feedback to a preexisting feature request issue. To speed the development process, you may also place a bounty on your favorite issues through Bountysource: https://www.bountysource.com/teams/owncloud

**Comment by DeepDiver1975** [comment]
@Kenarso integration with other apps is the driving force for us to build the mail app. 

You are welcome to contribute.

I'm closing this issue - we shall have more detailed feature request - if not yet available

**Comment by jancborchardt** [comment]
@Kenarso a bit of searching in the issues brings these to light:
* Ability to add event/ics attachments directly to the calendar https://github.com/owncloud/mail/issues/79 
* Ability to add people to Contacts https://github.com/owncloud/mail/issues/363
* Special folder »Contacts« with subfolders for each group https://github.com/owncloud/mail/issues/394
* and more ;)
