### ISSUE TITLE
Invalid request token of cached HTML messages

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/mail#767]
HTML messages are loaded via a URL that contains a request token. As this token is only valid for the current session, there are errors if you log out and in again:
![Error on Firefox](https://cloud.githubusercontent.com/assets/1374172/8148379/c600933a-129a-11e5-9d52-cf95e18b839e.png)

I'm thinking of the following possibilities to solve this:
- don't cache HTML messages (takes more time to load because there are two server requests needed instead of only one)
- use session storage instead of local storage as it isn't persistent
- cache HTML message body and load it as data source (PR #768)

@jancborchardt can you reproduce this? I guess you are using the current master of the mail app :)

**Comment by jancborchardt** [comment]
Yeah, I also had that for some emails and was wondering! Something about »Too many redirects«.

**Comment by jancborchardt** [comment]
Regarding how to resolve this, input from @DeepDiver1975 @irgendwie @aidanamavi is needed.

**Comment by jancborchardt** [comment]
@LukasReschke needs to look at this it seems.

**Comment by LukasReschke** [comment]
> I'm thinking of the following possibilities to solve this:
> don't cache HTML messages (takes more time to load because there are two server requests needed instead of only one)
> use session storage instead of local storage as it isn't persistent
> cache HTML message body and load it as data source (PR #768)
> @jancborchardt can you reproduce this? I guess you are using the current master of the mail app :)

Hehe, stumbled upon this on my PR https://github.com/owncloud/mail/pull/701 as well.

So what basically happens here is a part of our security model to prevent XSS, in the past we used sandboxed iframes instead of CSP. In this case the only protection was that an attacker didn't knew the link as the requesttoken is secret and changes with each session refresh. – I will get rid of this.

Nowadays we have CSP and do not rely on this anymore. But what remains is that for proxied contents we really want to have this as well. Let me think about a way to get rid of this as well here for proxied content such as images.

**Comment by LukasReschke** [comment]
Partially resolved at https://github.com/owncloud/mail/pull/793, for images and Co. we still need to think about a solution :see_no_evil:

**Comment by jancborchardt** [comment]
Seems to be fixed.
