### ISSUE TITLE
Mailto composer template

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/mail#844]
The composer (opened if you click mailto links) doesn't render the template correctly:
![bildschirmfoto von 2015-07-07 08 36 43](https://cloud.githubusercontent.com/assets/1374172/8540200/86a5e032-2483-11e5-866d-c74d1d7b6991.png)

1. Attachment template does not show the actual file name, ``{{displayName}}`` is shown instead
2. Send button should be inside the composer's textarea

**Comment by jancborchardt** [comment]
The positioning issue of the Send button is caused by it being in the same div (`.composer-fields`) as the attachment elements (`.new-message-attachments`). For the reply layout this is not the case.

In any case I’d say the layout part of this issue is minor. We should fix the `displayName` stuff though.
