### ISSUE TITLE
Message deletion triggered while adding account

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/mail#912]
If you use the delete key while adding a second account, the currently opened message is being deleted. This is pretty critical because you may delete newly arrived mails while setting up this app without noticing anything!

@DeepDiver1975 @jancborchardt 0.2 or 0.3?

**Comment by jancborchardt** [comment]
Seems like to fix this we need a simple check if a message is open at all. So 0.2 if it’s simple enough.

Otherwise 0.3 is fine since this only occurs on multi-account setup, during the setup process, when pressing the delete key. So actually I’ll move it to 0.3 already – if someone feels the need they can always fix it.
