### ISSUE TITLE
Why another mail app?

### ISSUE THREAD

**Issue by farson2003** [owncloud/mail#914]
Ok...
Very straightforward issue (I do not mean to discredit the hard work!):
Why is energy invested to develop another mail app? Many other apps exist, which integrate well in OC (for example RainLoop).

So why this development? Sorry if I am offending. But its an open question.

**Comment by jancborchardt** [comment]
@farson2003 some of the reasons:

* we’ve been working on this since a few years, so lots of other solutions haven’t been around
* goal is very tight integration with other ownCloud apps – Files, Contacts, Calendar, as well as with the look and feel of ownCloud. We can only really achieve that by making our own app.
* Rainloop was not open source until recently, and the design also doesn’t fully fit ownCloud. Sure it might integrate a bit, but I wouldn’t call it »well« at all.
* Roundcube doesn’t have multi-account support, which is crucial for any mail app. Also the design isn’t sufficiently simple and frictionless.
* we don’t fully reinvent the wheel but build on the open source Horde libraries. So no worries.
* using other apps would likely introduce additional dependencies beyond PHP, depending on what the app is written in.

Hope that answers the question. cc @DeepDiver1975 @ChristophWurst if you have anything to add.

**Comment by clementhk** [comment]
Well I looked into this project because I was looking for a full user-oriented solution, which means everything in that site should have everything that is user-oriented, meaning belong to/manage by end-users directly which admin/IT will not be involved and we want to make sure we are not using 3rd-party solution like dropbox that users can take data away by accident when they leave the company.
To us, an end-user would need,
 * Everything active sync provides
   * Email
   * Contacts
   * Tasks
   * Calendar (Team/user)
   * etc
 * Dropbox-like solution + sharing with AD users/AD groups/contacts without exchanging contacts
 * Google App-like cooperative edit doc
 * irc-like solution (like atlassian hipchat) for AD users/AD groups to communicate without exchanging contacts

And the system requirement would be we should be able to work online, user-friendly, well maintained, up to date.

To meet all these requirement is not easy, owncloud is one of the closest, and one of the most open source friendly one.

**Comment by DeepDiver1975** [comment]
I guess all has been said -> close
