### ISSUE TITLE
Second identity not available directly after adding the account, reload necessary

### ISSUE THREAD

**Issue by tflidd** [owncloud/mail#943]
I added two accounts. When I go to "new message", I can create a new message. I can only use the sender from the first mail account.

Version: 0.1.3 from the app store
OC 8.1.1 (Debian 7, Apache, Mysql, SuSE repo)

edit: After a logout and login on owncloud, the second identity is availble.

**Comment by jancborchardt** [comment]
@tflidd yeah, I think this is known. Do you want to submit a pull request for that maybe? :)

**Comment by ChristophWurst** [comment]
Accounts array is set during initialization of the composer view: https://github.com/owncloud/mail/blob/master/js/mail.js#L1029. Therefore, no changes are populated later on because the view is reused.

I suggest we can fix that once we have some Backbone models/collections in place so we can react on those changes (account added/deleted/changed) easily.

**Comment by jancborchardt** [comment]
This has been fixed now. :)
